apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: httpbin
  annotations:
    github.com/project-slug: letzya/httpbin
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://raw.githubusercontent.com/letzya/httpbin/main/openapi.yaml
